page_blocks: []

_array_structures:
 page_blocks:
  - label: Call to Action
    icon: article
    value: 
     _id: cta
     title: Call to Action
     heading: This is a heading
     subtitle: This is a subtitle  
  - label: Banner Image
    icon: article
    value: 
      _id: banner
      featured-image_path: 
      featured-image-alt: This is an alt tag
      heading: This is a heading